[package]
name = "rpc-optimize"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
diesel = { version = "2.2.0", features = ["postgres"] }
rocket_sync_db_pools = { version = "0.1.0", features = [
    "diesel_postgres_pool",
] }
dotenvy = "0.15.7"
thiserror = "2.0.9"
